// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmRiK_CHnRAbSxfzyJFOmlcndJfgP5xsE',
    appId: '1:907642462024:web:5464bc35d3d2728dbedd7d',
    messagingSenderId: '907642462024',
    projectId: 'ticead88',
    authDomain: 'ticead88.firebaseapp.com',
    storageBucket: 'ticead88.appspot.com',
    measurementId: 'G-Q4HSH4HB09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANhdJynkrKXDGdWaw_Icmeoy7HVVqmlFA',
    appId: '1:907642462024:android:7650d2eca39f77b7bedd7d',
    messagingSenderId: '907642462024',
    projectId: 'ticead88',
    storageBucket: 'ticead88.appspot.com',
  );
}
